name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy:
    name: Build and Deploy API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -f FlowerBouquetWebAPI/Dockerfile -t hieu15402/flowerbouquetwebapi:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the Docker image to Docker Hub
        run: docker push hieu15402/flowerbouquetwebapi:latest
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker stop prn231-api || true
            docker rm prn231-api || true
            docker images --filter=reference='hieu15402/flowerbouquetwebapi' --format '{{.ID}} {{.Tag}}' | grep '<none>' | awk '{print $1}' | xargs -I {} docker rmi -f {}
            docker pull hieu15402/flowerbouquetwebapi
            docker run -d -p 8080:8080 --name prn231-api --restart always hieu15402/flowerbouquetwebapi
